dnd-side-project/dnd-12th-5-backend

- src/main/java/com/picktory/config/SecurityConfig.java
- src/main/java/com/picktory/domain/user/controller/UserController.java
CORS 에러 처리 및 카카오 로그인 인증 관련 수정
- SecurityConfig 수정
- 허용된 origin 목록 확장 (localhost:3000, localhost:8080 추가)
- OPTIONS 메소드 CORS 허용 목록에 추가
- 엔드포인트 권한 설정 리팩토링 (public/authenticated 분리)
- UserController 수정
- 카카오 로그인 엔드포인트 메소드 POST → GET 변경
- Request 파라미터 형식 @RequestBody → @RequestParam 변경
CORS 정책 위반 및 카카오 OAuth 리다이렉트 URI 불일치 문제 해결
- 현재 운영 환경에서 발생하는 SecurityConfig 빌드 오류 해결을 위한 변경사항 포함
- 로컬/운영 환경 모두에서 원활한 카카오 로그인 흐름을 위한 설정 통합
> [refactor]: CORS 에러 처리 및 controller 수정

- src/main/java/com/picktory/config/auth/AuthenticationService.java
- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/dto/BundleCreateRequest.java
- src/main/java/com/picktory/domain/bundle/dto/BundleRequest.java
- src/main/java/com/picktory/domain/bundle/dto/BundleResponse.java
- src/main/java/com/picktory/domain/bundle/entity/Bundle.java
- src/main/java/com/picktory/domain/bundle/enums/BundleStatus.java
- src/main/java/com/picktory/domain/bundle/enums/DeliveryCharacterType.java
- src/main/java/com/picktory/domain/bundle/enums/DesignType.java
- src/main/java/com/picktory/domain/bundle/repository/BundleRepository.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
- src/main/java/com/picktory/domain/gift/dto/GiftCreateRequest.java
- src/main/java/com/picktory/domain/gift/dto/GiftRequest.java
- src/main/java/com/picktory/domain/gift/dto/GiftResponse.java
- src/main/java/com/picktory/domain/gift/entity/Gift.java
- src/main/java/com/picktory/domain/gift/entity/GiftImage.java
- src/main/java/com/picktory/domain/gift/enums/GiftResponseTag.java
- src/main/java/com/picktory/domain/gift/repository/GiftImageRepository.java
- src/main/java/com/picktory/domain/gift/repository/GiftRepository.java
- src/test/java/com/picktory/bundle/service/BundleServiceTest.java
- src/test/java/com/picktory/support/config/jwt/TestJwtTokenProvider.java
> 
[유저서비스 로그 추가된 브랜치와 리베이스 완료]
보따리 최초 생성 API를 개발하였습니다.
JWT 기반 사용자 인증을 추가하여, 현재 로그인한 사용자 정보를 활용하도록 하였습니다.
최초 생성된 보따리에는 보따리명 외에도 선물객체들, 선물이미지 관련 데이터들이 포함됩니다.
- 코드 리뷰 반영 (유저서비스의 로그인한 사용자 가져오기 인증의 책임 분리를 완료했습니다.)
> 
- POST /api/v1/bundles 보따리 최초 생성 API 구현
- UserService.getCurrentActiveUser() 메서드 접근 제한자 변경 (private → public)
- BundleService.createBundle() JWT 기반 사용자 인증을 통해 유저 ID 저장
- BundleServiceTest 테스트 코드 작성 ([[@mock](https://github.com/mock)](https://github.com/mock)을 활용하여 사용자 인증 Mocking)
- 테스트용 JWT 토큰 생성 유틸리티 (TestJwtTokenProvider) 추가
- 선물 엔티티, dto 등 기본 구조
- 선물 이미지 엔티티, dto 등 기본 구조
> 
> 
- [🔺] 테스트 코드를 작성하였나요? -> 선물객체들, 선물이미지 관련 데이터들 포함 전 테스트 코드만 작성됨
> …
> Feature/bundle, 시큐리티, jwt, 로그 병합 완료

- build.gradle
> Hibernate Validator(Bean Validation Provider)가 없어서 Hibernate가 테이블을 생성하지 못하고 실패함. 
Spring Boot 3.0 이상에서는 jakarta.validation을 지원하므로, hibernate-validator를 build.gradle에 추가해야 해서 hibernate.validator 추가
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
> [build]: hibernate.validator 추가

- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/dto/BundleDeliveryRequest.java
- src/main/java/com/picktory/domain/bundle/dto/BundleRequest.java
- src/main/java/com/picktory/domain/bundle/dto/BundleResponse.java
- src/main/java/com/picktory/domain/bundle/entity/Bundle.java
- src/main/java/com/picktory/domain/bundle/repository/BundleRepository.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
- src/test/java/com/picktory/bundle/service/BundleServiceTest.java
배달부 캐릭터 선택 기능 구현
- BaseResponseStatus에 배달부 관련 예외코드 추가
- Bundle 엔티티 
- API 구현
- 서비스 로직
배달부 캐릭터 선택 기능
굳이 delivery 도메인으로 나눌 필요성을 못 느껴서 bundle 도메인에다 짰습니다.
도메인을 bundle과 delivery로 나눠야 할지는 고민이 되긴하네요
> [Feature/bundle delivery] 배달부 캐릭터 선택 구현

- build.gradle
- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/domain/gift/entity/Gift.java
- src/main/java/com/picktory/domain/gift/repository/GiftImageRepository.java
- src/main/java/com/picktory/domain/response/controller/ResponseController.java
- src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
- src/main/java/com/picktory/domain/response/entity/Response.java
- src/main/java/com/picktory/domain/response/entity/ResponseTag.java
- src/main/java/com/picktory/domain/response/repository/ResponseRepository.java
- src/main/java/com/picktory/domain/response/repository/ResponseRepositoryCustom.java
- src/main/java/com/picktory/domain/response/repository/ResponseRepositoryImpl.java
- src/main/java/com/picktory/domain/response/service/ResponseService.java
- src/test/java/com/picktory/response/service/ResponseServiceTest.java
보따리 조회 API 및 관련 기능을 구현하였습니다.  
- QueryDSL 기반의 데이터 조회 로직을 추가하여, 선물, 이미지, 응답 정보를 통합 조회할 수 있도록 하였습니다.  
- Response 엔티티 및 Repository, 서비스, API 엔드포인트를 구현하고 관련 테스트 클래스도 작성하였습니다.
- **QueryDSL 설정 및 의존성 추가:**  
QueryDSL을 통한 동적 쿼리 지원을 위해 `build.gradle` 파일에 관련 설정과 의존성을 추가하였습니다.
- **응답( Response ) 관련 구현:**  
- 기존 `GiftResponse` 파일을 제거하고, 새로운 `Response` 엔티티를 도입하였습니다.  
- 응답 태그 Enum 타입(`ResponseTag`) 및 응답 상태 필드를 추가하였습니다.  
- Response 리포지토리 인터페이스와 QueryDSL 기반 커스텀 구현체를 정의하였습니다.
- **보따리 조회 기능:**  
- 보따리 조회 API 엔드포인트를 구현하여, 선물, 이미지, 응답 정보를 통합 조회하는 서비스 로직을 작성하였습니다.  
- GiftImage 조회 리포지토리에 `findByGiftIdIn` 메서드를 추가하여, 관련 데이터 조회를 지원합니다.
- **테스트 코드:**  
ResponseService의 기본 테스트 클래스 구조를 구현하여, 향후 테스트 코드 작성의 기반을 마련하였습니다.
- 관련 이슈: [[#이슈번호](https://chatgpt.com/c/67af4ee9-4b4c-800c-983b-2d6ffa65af8a#)](#)  
(실제 이슈 번호가 …
> [Feature/bundle-open] 보따리 조회 기능 구현

- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/domain/bundle/dto/BundleDeliveryRequest.java
- src/main/java/com/picktory/domain/gift/dto/GiftResponse.java
- src/main/java/com/picktory/domain/response/controller/ResponseController.java
- src/main/java/com/picktory/domain/response/dto/SaveGiftResponsesRequest.java
- src/main/java/com/picktory/domain/response/dto/SaveGiftResponsesResponse.java
- src/main/java/com/picktory/domain/response/entity/Response.java
- src/main/java/com/picktory/domain/response/entity/ResponseTag.java
- src/main/java/com/picktory/domain/response/repository/ResponseRepository.java
- src/main/java/com/picktory/domain/response/service/ResponseService.java
- src/test/java/com/picktory/bundle/service/BundleServiceTest.java
- src/test/java/com/picktory/response/service/ResponseServiceTest.java
선물 보따리 답변 기능 구현: 응답 저장 및 조회 기능
- GiftResponseTag로 응답 태그 관리 체계 통합 (ResponseTag 제거)
- 선물 답변 저장 API 및 관련 DTO 구현
- SaveGiftResponsesRequest, SaveGiftResponsesResponse 추가
- `/gifts/{link}/answers` POST 엔드포인트 구현
- ResponseService에 다중 선물 답변 처리 로직 추가
- 번들 상태 검증
- 선물 목록 검증
- 기존 응답 여부 검증
- 모든 선물 응답 완료 여부 검증
- ResponseBundleDto에서 응답된 선물의 메시지 표시 로직 구현
- 테스트 코드 추가 및 개선
- 선물 답변 저장 성공/실패 케이스 테스트
- 보따리 조회 테스트 개선
선물 보따리 답변 기능 구현
> [Feature/response-answer] 보따리 답변 기능 구현

- src/main/java/com/picktory/domain/bundle/service/BundleService.java
> 
- 번들 링크 생성 시 불필요한 "/delivery/" 접두어 제거
- 기존 접두어로 인해 API 엔드포인트 경로와 불일치 발생
- API 엔드포인트: /api/v1/responses/bundles/{link}
- 링크 생성 시 UUID 문자열만 반환하도록 수정
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
> [fix]: 링크 생성 시 "/delivery/" 접두어 제거

- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/dto/BundleSummaryResponse.java
- src/main/java/com/picktory/domain/bundle/dto/GiftThumbnailResponse.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
> 보따리 간이 조회 api 개발했습니다. 보따리 결과 조회와 크게 다르지 않았습니다.
> 
> # 11. 보따리 간이 조회 API
> GET /api/v1/bundles/{id}
> 
> ### 설명
> - 특정 보따리의 정보를 간이 조회하는 API
> - 보따리의 이름(name), 디자인 타입(designType), 상태(status), 배달 링크(link) 포함
> - 보따리에 포함된 선물 목록과 각 선물의 대표 이미지(썸네일) 제공
> - 보따리 상태가 `DRAFT`일 경우 `link`는 `null`
> - 각 선물의 `isPrimary = true`인 `GiftImage.imageUrl`을 썸네일로 제공
> - 인증된 사용자만 사용 가능 (Authorization 헤더 필요)
> (백엔드에서 status=COMPLETED(답변 완료된 보따리)상태일 때 사용자가 이 API 최초 호출 시, isRead=true로 변경함)
> 
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
-> 보따리 상태가 DRAFT여서 Link가 null인 경우, 이외 상태라서 링크가 있는 경우, status=COMPLETED(답변 완료된 보따리)상태일 때 사용자가 이 API 최초 호출 시, isRead=true로 변경되는 경우 모두 Postman으로 확인했습니다.
> 
> 예시: …
> [feat]: 보따리 간이 조회

- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
- src/main/java/com/picktory/domain/gift/dto/GiftDetailResponse.java
- src/main/java/com/picktory/domain/gift/repository/GiftRepository.java
- src/test/java/com/picktory/bundle/service/BundleServiceTest.java
보따리 개별 선물 조회 API를 구현했습니다. 특정 보따리에 포함된 개별 선물을 조회할 수 있으며, 선물의 기본 정보와 함께 대표 이미지(썸네일)와 추가 이미지 목록을 제공합니다.
- GiftDetailResponse DTO 생성 (썸네일과 이미지 목록 분리)
- GiftRepository에 findByIdAndBundleId 메서드 추가
- BaseResponseStatus에 GIFT_NOT_FOUND 에러 코드 추가
- BundleController에 개별 선물 조회 API 엔드포인트 추가
- BundleService에 개별 선물 조회 로직 구현
- 상세 단위 테스트 케이스 추가
보따리 개별 선물 조회 API 구현
- 성공 케이스, 권한 없음, 리소스 없음 등 모든 시나리오 테스트 완료
- API 문서에 새로운 엔드포인트 정보 추가
- 없음
- 완료
> [Feature/individual-gift-inquiry] : 보따리 개별 조회 기능 구현

- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
- src/main/java/com/picktory/domain/gift/dto/DraftGiftsResponse.java
- src/main/java/com/picktory/domain/gift/repository/GiftImageRepository.java
- src/test/java/com/picktory/bundle/service/BundleServiceTest.java
임시 저장된 보따리(DRAFT 상태)의 선물 목록을 조회하는 API를 구현했습니다. 해당 API는 선물의 기본 정보와 함께 대표 이미지(썸네일) 및 추가 이미지 목록을 제공합니다.
- DraftGiftsResponse DTO 구현
- 선물 목록과 각 선물별 이미지 정보를 효율적으로 매핑
- 썸네일과 일반 이미지 구분 처리
- GiftImageRepository에 벌크 이미지 조회 메서드 추가
- N+1 문제 해결을 위한 findByGiftIds 메서드 구현
- BundleController/Service에 임시 저장 선물 목록 조회 API 추가
- DRAFT 상태 검증 로직 구현
- 권한 검증 및 예외 처리
- 단위 테스트 케이스 추가
- 성공/실패 시나리오 테스트 구현
임시 저장된 보따리 선물 목록 조회 API 구현
- 성공 케이스, DRAFT 상태 검증, 권한 검증 등 테스트 완료
- API 문서에 새로운 엔드포인트 정보 추가
- 없음
- 완료
> [Feature/bundle-draft-gifts]: 보따리 마저 채우기 기능 구현

- src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
- src/test/java/com/picktory/response/service/ResponseServiceTest.java
보따리 조회 API 응답에 design_type 필드를 추가하여 배달부 SVG 변경에 필요한 보따리 색상 정보를 제공합니다.
- ResponseBundleDto.BundleInfo에 design_type 필드 추가
- fromEntity 메서드에서 Bundle의 designType을 ResponseBundleDto에 매핑하는 로직 구현
- ResponseServiceTest에 design_type 필드 반환값 검증 로직 추가
보따리 조회 기능 구현
- ResponseBundleDto에 design_type 필드 추가로 인한 API 응답 변경사항을 확인해주세요
- 테스트 코드의 검증 로직이 적절한지 리뷰 부탁드립니다
해당 PR은 배달부 SVG가 보따리 색상에 따라 동적으로 변경되어야 하는 요구사항을 반영하기 위한 작업입니다. 기존 Bundle 엔티티에 있던 designType 정보를 API 응답에 포함시켜 프론트엔드에서 활용할 수 있도록 구현하였습니다.
> [fix]: 보따리 design_type 필드 추가

- src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
- src/test/java/com/picktory/response/service/ResponseServiceTest.java
보따리 조회 API 응답 데이터 구조 개선
- 선물 name 필드 추가
- 썸네일 이미지를 imageUrls에도 포함하도록 수정
- 첫 번째 이미지를 썸네일로 사용하도록 변경
- 관련 테스트 코드 수정
#28 보따리 조회 기능 구현
- 프론트엔드팀의 요청사항을 반영하여 이미지 URL 처리 로직을 수정했습니다
- 기존 isPrimary 플래그는 유지하되 실제 동작은 첫 번째 이미지를 썸네일로 사용하도록 변경했습니다
> [refactor]: 보따리 조회 응답 데이터 수정

- src/main/java/com/picktory/config/s3/S3Config.java
- src/main/java/com/picktory/domain/gift/service/S3Service.java
> S3 이미지 조회 시 cloudfront(CDN)사용하도록 수정했습니다.
지금은 이미지 URL에 S3 버킷명이 그대로 노출되고 있는데,
사용자가 S3 이미지 주소에 다이렉트로 접근해서 버킷명이 노출되면 DDoS 공격 등에 위험하고, 과금도 쉽게 돼
보통은 중간에 CloudFront 같은 CDN을 프록시처럼 두고 이미지 조회를 처리하는 게 일반적이라고 알고 있습니다.
이렇게 하면 S3 버킷명을 숨길 수 있고, 성능 최적화(DDoS 방어 포함)에도 유리해요. 특히 트래픽이 많아질 경우 CloudFront가 캐싱 역할을 해서 S3 직접 접근보다 속도도 빨라지고 비용도 절감할 수 있다고 하여 수정했습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
> S3 이미지 조회 시 cloudfront(CDN)사용

- src/main/java/com/picktory/config/SecurityConfig.java
- src/main/java/com/picktory/config/jwt/JwtAuthenticationFilter.java
- 구현 기능: 비회원 보따리 조회 API 접근 허용
- 구현 내용:
- 비회원이 공유 링크를 통해 보따리를 조회할 수 있도록 인증 로직 수정
- SecurityConfig 및 JwtAuthenticationFilter에 보따리 조회 API 경로 추가
- 변경 사항:
- SecurityConfig의 getPublicEndpoints()에 "/api/v1/responses/bundles/**" 경로 추가
- JwtAuthenticationFilter의 shouldNotFilter()에 해당 경로 추가
- 테스트 환경: 로컬
- 테스트 결과:
- 공유 링크를 통한 보따리 접근 시 403 에러 해결
- 비회원 상태에서 정상적으로 API 응답 확인
- API 문서상 "비회원도 접근 가능한 공개 API"로 명시되어 있어 인증 없이 접근 가능하도록 수정
- 리뷰 포인트:
> [fix]: 보따리 조회 API 접근 403 에러 해결

- src/main/java/com/picktory/domain/gift/dto/DraftGiftsResponse.java
보따리 마저 채우기 API와 보따리 조회 API 간 썸네일 처리 로직 통일
- `DraftGiftsResponse` 클래스에서 썸네일 결정 로직 변경 (첫 번째 이미지를 썸네일로 사용)
- 모든 이미지 URL을 `imageUrls`에 포함하도록 수정
- PR #45에서 구현된 `DraftGiftsResponse` 클래스의 썸네일 처리 로직을 PR #51의 방식과 일치시켰습니다
- 기존 `isPrimary` 플래그는 그대로 유지했지만 실제 동작은 첫 번째 이미지를 썸네일로 사용합니다
- 테스트 코드는 이미 PR #51 방식으로 구현되어 있어 추가 수정은 불필요했습니다
- 이 변경으로 보따리 관련 모든 API에서 일관된 응답 형식을 유지할 수 있게 됩니다
- 프론트엔드와의 인터페이스 일관성을 위해 필요한 변경입니다
> [fix]: 보따리 마저 채우기 API 썸네일 로직 통일

- src/main/java/com/picktory/domain/bundle/service/BundleService.java
- src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
보따리 조회 API 응답에 보따리 ID를 추가하여 답변 저장하기 API와의 연동을 개선했습니다.
- ResponseBundleDto에 bundle.id 필드 추가
#42 - 답변 저장하기 API 연동 이슈
- ResponseBundleDto 구조에 ID 필드만 추가했으므로 기존 로직에 영향이 없습니다
- API 문서도 함께 업데이트했으니 확인 부탁드립니다
> [fix]: 보따리 풀어보기 API 응답에 보따리 ID 추가

- src/main/java/com/picktory/domain/gift/entity/Gift.java
- src/main/java/com/picktory/domain/response/service/ResponseService.java
> Response 엔티티가 따로 존재하고 있어, 보따리 결과 조회시 선물별 responseTag가 매핑되고 있지 않아  Gift 엔티티에도 responseTag 저장되도록 급히 수정합니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
> [refactor]: Gift 엔티티에도 responseTag 저장되도록 수정

- src/main/java/com/picktory/config/jwt/JwtTokenProvider.java
> jwt 엑세스 토큰 시간을 1-> 24시간으로 변경함.
만료되었을 때 자동으로 refreshToken 사용해서 다시 accessToken 재발급받는 api가 현재 없고, accessToken 만료 시 따로 로그아웃되지 않고 있어 토큰 만료 시간을 늘림.
> [hotfix]: jwt 엑세스 토큰 시간 변경

- src/main/java/com/picktory/common/error/handler/GlobalExceptionHandler.java
> 기존 GlobalExceptionHandler가 서비스 로직에서 예외 발생시 메시지를 같이 반환하지 않는 부분이 있어서 추가했습니다
> [feat]: BaseException 전역 예외 처리 로직 추가 - BaseResponse 형식으로 일관된 에러 응답 반환

- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/config/auth/AuthenticationService.java
- src/main/java/com/picktory/domain/auth/controller/AuthController.java
- src/main/java/com/picktory/domain/auth/dto/TokenDto.java
- src/main/java/com/picktory/domain/auth/oauth/client/KakaoClient.java
- src/main/java/com/picktory/domain/auth/refresh/service/RefreshTokenService.java
- src/main/java/com/picktory/domain/auth/service/AuthService.java
- src/main/java/com/picktory/domain/user/entity/User.java
인증 관련 예외 처리를 BaseException으로 통일하여 일관된 에러 처리 시스템 구축
- IllegalStateException, IllegalArgumentException 등을 BaseException으로 변경
- 에러 응답을 BaseResponseStatus 열거형으로 표준화
- 토큰 만료 예외 처리를 위한 EXPIRED_REFRESHTOKEN 상태 추가
- 에러 메시지 한글화 및 일관성 유지
#67 리프레시 토큰 예외 처리 개선
- AuthService, RefreshTokenService 등의 모든 예외를 BaseException을 통해 표준화했습니다.
- 기존 코드와의 호환성을 위해 BaseResponse를 이용한 응답 형식을 유지했습니다.
- 토큰 만료시 프론트엔드에서 재로그인 요청을 해야함을 명확히 알 수 있도록 메시지를 수정했습니다.
리프레시 토큰 관련 플로우:
1. 리프레시 토큰 만료 시 → EXPIRED_REFRESHTOKEN 예외 발생 → 재로그인 요청
2. 리프레시 토큰 검증 실패 시 → INVALID_JWT 예외 발생
3. 사용자를 찾을 수 없을 때 → USER_NOT_FOUND 예외 발생
> [refactor]: 인증 관련 예외 처리를 BaseException으로 통일

- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/config/auth/AuthenticationService.java
- src/main/java/com/picktory/domain/auth/controller/AuthController.java
- src/main/java/com/picktory/domain/auth/dto/TokenDto.java
- src/main/java/com/picktory/domain/auth/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/picktory/domain/auth/oauth/client/KakaoClient.java
- src/main/java/com/picktory/domain/auth/refresh/service/RefreshTokenService.java
- src/main/java/com/picktory/domain/auth/service/AuthService.java
- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/dto/BundleDto.java
- src/main/java/com/picktory/domain/bundle/dto/BundleListResponse.java
- src/main/java/com/picktory/domain/bundle/dto/BundleMainListResponse.java
- src/main/java/com/picktory/domain/bundle/dto/BundleRequest.java
- src/main/java/com/picktory/domain/bundle/dto/BundleResponse.java
- src/main/java/com/picktory/domain/bundle/entity/Bundle.java
- src/main/java/com/picktory/domain/bundle/repository/BundleRepository.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
- src/main/java/com/picktory/domain/gift/enums/GiftResponseTag.java
- src/main/java/com/picktory/domain/gift/repository/GiftImageRepository.java
- src/main/java/com/picktory/domain/gift/repository/GiftRepository.java
- src/main/java/com/picktory/domain/gift/service/GiftService.java
- src/main/java/com/picktory/domain/response/service/ResponseService.java
- src/main/java/com/picktory/domain/user/entity/User.java
- src/test/java/com/picktory/bundle/controller/BundleControllerTest.java
- src/test/java/com/picktory/bundle/service/BundleServiceIntegrationTest.java
- src/test/java/com/picktory/bundle/service/BundleServiceTest.java
- src/test/java/com/picktory/bundle/service/BundleUpdateTest.java
- src/test/java/com/picktory/response/service/ResponseServiceTest.java
선물 응답 API 403 오류 해결 및 응답 태그 UI 변경에 따른 enum 매핑 업데이트
- JWT 필터에 '/api/v1/responses/bundles' 경로를 PUBLIC_PATHS에 추가하여 403 Forbidden 오류 해결
- UI에서 변경된 선물 응답 태그에 맞게 GiftResponseTag enum 값 업데이트
- "정말 최고에요" 태그 추가
> [fix]: JWT 필터에 선물 응답 API 경로 추가 및 응답 태그 변경

- src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
`ResponseBundleDto` 내 필드명을 스네이크 케이스에서 카멜 케이스로 변경하여 Java 네이밍 컨벤션을 준수하도록 리팩토링했습니다.
- `delivery_character_type` → `deliveryCharacterType`
- `design_type` → `designType`
- `total_gifts` → `totalGifts`
- `fromEntity` 메서드 내 필드 매핑 로직 수정
- `ResponseBundleDto` 전체적으로 카멜 케이스 적용
> 없음 (또는 관련 이슈가 있다면 여기에 기재)
> UI 변경사항 없음
- Java 코드 스타일에 맞게 필드명을 통일하였으며, 기존에 API 응답과 불일치하던 네이밍 이슈를 해소하였습니다.
> [refactor]: ResponseBundleDto 필드 카멜 케이스 네이밍 적용

- .github/workflows/deploy-api.yml
- .github/workflows/deploy.yml
기존 main 브랜치에 push될 때 개발용 API 서버(dev-api.picktory.net)로 자동 배포되던 deploy.yml은 주석 처리했습니다.
대신, 새로운 워크플로우 파일인 deploy-api.yml을 추가하여,
develop 브랜치에 push될 때 개발용 API 서버(api.picktory.net, picktory.service)에 자동 배포되도록 설정했습니다.
앞으로는 develop 브랜치에서 개발하고, 이 브랜치에 push하면 개발용 API 서버가 자동으로 갱신됩니다.
운영용 서비스(dev-api.picktory.net, picktory-dev.service)는 여전히 main 브랜치를 통해 관리되며,
main 브랜치에 push되더라도 자동 배포는 발생하지 않습니다.
> [CI/CD] develop 브랜치 push 시 api.picktory.net 자동 배포 설정

- src/main/java/com/picktory/domain/gift/enums/GiftResponseTag.java
- src/test/java/com/picktory/response/service/ResponseServiceTest.java
- 구현 기능: 선물 답변저장하기
- 구현 내용:
- ResponseServiceTest 클래스 수정
- Bundle 엔티티와 테스트 코드 사이의 불일치 해결
- 레포지토리 메소드 이름 일치시킴 (findAllByBundleId, findAllByGift_IdIn 등)
- Gift 객체 처리 로직 추가
- 변경 사항:
- User 관계 수정 (userId → User 객체 사용)
- message 필드 검증 로직 수정
- COMPLETED 상태 처리 로직 수정
- 테스트 환경: 로컬
- 테스트 결과: ResponseServiceTest 관련 테스트 모두 통과
- 다른 테스트(BundleServiceIntegrationTest, KakaoClientTest)는 여전히 실패하지만 이 PR의 범위에 포함되지 않음
- 리뷰 포인트:
- 테스트 코드와 실제 구현 간의 일치성
- User 관계 처리 방식의 적절성
> [test]: 답변저장 테스트 코드 수정

- src/test/java/com/picktory/user/service/KakaoClientTest.java
- 구현 기능: 카카오 클라이언트 테스트 수정
- 구현 내용:
- KakaoClientTest 클래스의 예외 처리 로직 수정
- IllegalStateException에서 BaseException으로 예외 타입 변경
- 예외 메시지 검증 대신 BaseResponseStatus 검증으로 수정
- 변경 사항:
- testGetKakaoAccessToken_EmptyResponse() 테스트 로직 수정
- testGetKakaoAccessToken_HttpError() 테스트 로직 수정
- KAKAO_API_ERROR 및 INVALID_JWT 상태 코드 검증 추가
- 테스트 환경: 로컬
- 테스트 결과: KakaoClientTest 관련 테스트 모두 통과
- 실제 구현은 변경하지 않고 테스트 코드만 수정했습니다
> [test]: 카카오 클라이언트 테스트 예외 타입 수정

- src/main/java/com/picktory/common/BaseResponseStatus.java
- src/main/java/com/picktory/domain/bundle/dto/BundleRequest.java
- src/main/java/com/picktory/domain/bundle/dto/BundleUpdateRequest.java
Bundle 생성 시 최소 선물 개수 요구사항을 완화하는 작업을 수행했습니다.
- BundleRequest DTO의 gifts 필드 최소 개수 제한을 1개로 변경
- 보따리(Bundle)에 최소 1개, 최대 6개의 선물 담을 수 있도록 수정
- 유효성 검사 메시지 업데이트
이 변경은 사용자 피드백을 반영한 것으로, 보따리 생성 시 선물을 더 적게 담을 수 있도록 하여 사용자 경험을 개선하였습니다.
> [fix]: Bundle 생성 시 최소 선물 개수 요구사항 변경

- src/main/java/com/picktory/domain/bundle/controller/BundleController.java
- src/main/java/com/picktory/domain/bundle/dto/BundleNameUpdateRequest.java
- src/main/java/com/picktory/domain/bundle/entity/Bundle.java
- src/main/java/com/picktory/domain/bundle/service/BundleService.java
보따리 이름만 수정할 수 있는 새로운 PATCH API를 구현했습니다. 기존 PUT API는 선물 목록 수정 용도로 남겨두고, 이름 수정은 별도 API로 분리하여 효율성을 개선했습니다.
- PATCH `/api/v1/bundles/{bundleId}` 엔드포인트 구현
- 보따리 이름만 수정하기 위한 `BundleNameUpdateRequest` DTO 생성
- `BundleController`에 이름 수정 메소드 추가
- `BundleService`에 이름 수정 로직 구현
관련 이슈 없음
이 변경은 보따리 이름만 수정하고 싶을 때 불필요하게 전체 선물 리스트를 요청에 포함시켜야 하는 문제를 해결합니다. 보따리 상태가 DRAFT일 때만 이름 수정이 가능하도록 제한했습니다.
> [feat]: 보따리 이름 수정 API 추가
