build.gradle, src/main/java/com/picktory/PicktoryApplication.java, src/main/java/com/picktory/common/BaseEntity.java, src/main/java/com/picktory/common/BaseResponse.java, src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/config/RestTemplateConfig.java, src/main/java/com/picktory/config/SecurityConfig.java, src/main/java/com/picktory/domain/user/controller/UserController.java, src/main/java/com/picktory/domain/user/dto/KakaoTokenResponse.java, src/main/java/com/picktory/domain/user/dto/KakaoUserInfo.java, src/main/java/com/picktory/domain/user/dto/UserLoginRequest.java, src/main/java/com/picktory/domain/user/dto/UserLoginResponse.java, src/main/java/com/picktory/domain/user/dto/UserResponse.java, src/main/java/com/picktory/domain/user/entity/User.java, src/main/java/com/picktory/domain/user/repository/UserRepository.java, src/main/java/com/picktory/domain/user/service/UserService.java
카카오 소셜 로그인 기능 구현 및 사용자 인증 시스템 개발
1. 카카오 OAuth 인증 플로우 구현
- 인증 코드로 카카오 액세스 토큰 발급
- 카카오 사용자 정보 조회
- JWT 토큰 발급 및 인증 처리
2. 사용자 관리 기능 구현
- 회원가입/로그인 통합 프로세스
- 내 정보 조회 API
- 로그아웃 API
- 회원 탈퇴 API
3. 보안 설정 추가
- Spring Security 설정
- JWT 인증 필터 구현
- CORS 설정
- [] 테스트 코드를 작성하였나요?
- API 문서 업데이트 완료
- README.md 환경 설정 가이드 추가
- 인증이 필요한 API에 대해 JWT 토큰 필수
- Google Java Style Guide 준수
- CheckStyle 검사 완료
1. 토큰 관리 전략
2. 보안 관련
3. 에러 처리
1. 환경 설정
- application.yml에 카카오 API 관련 설정 추가 필요
```yaml
kakao:
client:
id: ${KAKAO_CLIENT_ID}
redirect:
uri: ${KAKAO_REDIRECT_URI}
```
- JWT 시크릿 키 환경 변수로 설정
2. 테스트 방법
=> [Feature/kakao login] 카카오 OAUTH 로그인 구현 완료

build.gradle, src/main/java/com/picktory/PicktoryApplication.java, src/main/java/com/picktory/common/BaseEntity.java, src/main/java/com/picktory/common/BaseResponse.java, src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/config/RestTemplateConfig.java, src/main/java/com/picktory/config/SecurityConfig.java, src/main/java/com/picktory/domain/user/controller/UserController.java, src/main/java/com/picktory/domain/user/dto/KakaoTokenResponse.java, src/main/java/com/picktory/domain/user/dto/KakaoUserInfo.java, src/main/java/com/picktory/domain/user/dto/UserLoginRequest.java, src/main/java/com/picktory/domain/user/dto/UserLoginResponse.java, src/main/java/com/picktory/domain/user/dto/UserResponse.java, src/main/java/com/picktory/domain/user/entity/User.java, src/main/java/com/picktory/domain/user/repository/UserRepository.java, src/main/java/com/picktory/domain/user/service/UserService.java, src/test/java/com/picktory/support/DatabaseCleaner.java, src/test/java/com/picktory/support/DatabaseCleanerExtension.java, src/test/java/com/picktory/support/annotation/ServiceTest.java, src/test/java/com/picktory/support/config/TestConfig.java, src/test/java/com/picktory/user/service/UserServiceTest.java
- 구현 기능: 카카오 로그인 테스트 환경 구성 및 DB 초기화 기능 개선
- **구현 내용:**
- 테스트 코드 환경 설정 및 DB 초기화 기능 구현  
- `DatabaseCleaner.java`: 엔티티 메타모델을 활용하여 모든 테이블을 탐색, TRUNCATE 및 ID 재시작 로직 구현  
- `DatabaseCleanerExtension.java`: JUnit 5 `BeforeEachCallback`을 활용해 테스트 전 데이터 클린업 실행  
- `ServiceTest.java`: `@SpringBootTest`와 `DatabaseCleanerExtension`을 포함하는 커스텀 테스트 어노테이션 구현  
- `TestConfig.java`: 테스트 전용 빈(DatabaseCleaner) 등록
- `UserServiceTest.java`: 카카오 로그인(신규/기존), 로그아웃, 내 정보 조회, 탈퇴 기능에 대한 단위 테스트 구현 (모킹 처리 및 `SecurityContextHolder` 활용)  
- **변경 사항:**
- **스크린샷/영상:**
- (해당되는 경우 실행 결과 스크린샷 또는 로그 첨부)
- **테스트 환경:**
- 로컬 개발 환경 (IntelliJ, Gradle, JUnit 5)
- **테스트 결과:**
- 모든 단위 테스트(UserServiceTest 포함) 성공
- **테스트 증빙:**
- (필요 시 스크린샷이나 로그 첨부)
- **리뷰 포인트:**
- **논의가 필요한 부분:**
=> [Feature/kakao login test] 카카오 로그인 테스트 및 테스트코드 관련 설정 구현 완료

src/main/java/com/picktory/config/SecurityConfig.java
> 세션 비활성화 코드 추가함. 루트 URL 부터 발생하는 403에러를 해결하기 위해 jwt 기반 인증이기에 세션 비활성화 코드를 추가함. 
> - SessionCreationPolicy.STATELESS 추가
> 
> 예시:
=> [fix]: STATELESS 세션 비활성화

src/main/java/com/picktory/config/SecurityConfig.java, src/main/java/com/picktory/config/jwt/JwtAuthenticationFilter.java
> 스프링 시큐리티 및 JwtAuthenticationFilter 리팩토링
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: 스프링 시큐리티 및 JwtAuthenticationFilter 리팩토링

src/main/java/com/picktory/config/SecurityConfig.java
> 현상님 PR 머지하니, STATELESS 세션 비활성화 코드가 삭제돼서 재추가함
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: STATELESS 세션 비활성화 재적용

src/main/java/com/picktory/config/SecurityConfig.java, src/main/java/com/picktory/config/jwt/JwtAuthenticationFilter.java, src/main/java/com/picktory/controller/RootController.java
> RootController를 만들어 루트 페이지 겟매핑 추가. 
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: 루트 페이지 GetMapping 추가

src/main/java/com/picktory/domain/user/service/UserService.java
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: userservice 로그 출력

build.gradle
mysql-connector-j가 제대로 빌드되지 않고 있었음
=> [build] implementation 'com.mysql:mysql-connector-j:8.0.33'로 수정 및 h2 삭제

src/main/java/com/picktory/domain/bundle/controller/BundleController.java, src/main/java/com/picktory/domain/bundle/dto/BundleMainListResponse.java, src/main/java/com/picktory/domain/bundle/repository/BundleRepository.java, src/main/java/com/picktory/domain/bundle/service/BundleService.java, src/test/java/com/picktory/bundle/controller/BundleControllerTest.java
> 메인 보따리 조회 api
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> Feature/bundle 메인 보따리 8개 조회

src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/domain/bundle/service/BundleService.java
> 기존 PR을 병합하는 과정에서 발생했던 conflict를 해결하였습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: merge-conflict 해결

src/main/java/com/picktory/domain/bundle/service/BundleService.java, src/main/java/com/picktory/domain/gift/dto/AbstractGiftRequest.java, src/main/java/com/picktory/domain/gift/dto/GiftRequest.java, src/main/java/com/picktory/domain/gift/dto/GiftUpdateRequest.java, src/main/java/com/picktory/domain/gift/entity/Gift.java, src/main/java/com/picktory/domain/gift/entity/GiftImage.java, src/main/java/com/picktory/domain/gift/repository/GiftImageRepository.java
> 남아 있던 PR 머지 후 배달부, 보따리 조회 및 선물 관련 comflict 해결했습니다. gift 관련된 "}" 누락 등 고쳤고, gift 관련 꼬인 부분 코드 수정했습니다.
기존 내용은 최대한 살리면서 코드 덧붙이는 식으로 해결해서 추후 refactor 필요할 듯합니다.
ResponseServiceTest 는 동작하는 것을 확인했는데, BundleServiceTest에서의 배달부 테스트는 동작하지 않는데 확인 부탁드립니다ㅠㅠ
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: 배달부, 보따리 조회 및 선물 관련 comflict 해결

src/main/java/com/picktory/domain/bundle/dto/BundleDeliveryRequest.java, src/test/java/com/picktory/bundle/service/BundleServiceTest.java
> 기존에 에러가 있었던 응답 서비스 및 배달부 설정 테스트 코드를 수정하여 적용하였습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: 응답 서비스 테스트 리팩토링

build.gradle, src/main/java/com/picktory/config/auth/AuthenticationService.java, src/main/java/com/picktory/config/s3/S3Config.java, src/main/java/com/picktory/domain/bundle/controller/BundleController.java, src/main/java/com/picktory/domain/bundle/service/BundleService.java, src/main/java/com/picktory/domain/gift/controller/S3Controller.java, src/main/java/com/picktory/domain/gift/dto/s3/PresignedUrlRequest.java, src/main/java/com/picktory/domain/gift/dto/s3/PresignedUrlResponse.java, src/main/java/com/picktory/domain/gift/entity/GiftImage.java, src/main/java/com/picktory/domain/gift/repository/GiftImageRepository.java, src/main/java/com/picktory/domain/gift/service/S3Service.java
> 이미지 업로드용 AWS S3 presignedUrl 발급 로직을 postman에서 테스트하여 정상작동합니다.
기존 AuthenticationService 의 getAuthenticatedUser() 이 잘못 변경됐어서 변수 타입을 바꿨고 정상 동작합니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [feat]: 이미지 업로드용 AWS S3 presignedUrl 발급

src/main/java/com/picktory/config/SecurityConfig.java, src/main/java/com/picktory/config/jwt/JwtAuthenticationFilter.java
> 카카오 콜백 URL 추가 설정해두었습니다!
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: 카카오 콜백 URL 추가 설정

src/main/java/com/picktory/domain/user/entity/User.java, src/main/java/com/picktory/domain/user/repository/UserRepository.java, src/main/java/com/picktory/domain/user/service/UserService.java, src/test/java/com/picktory/bundle/service/BundleServiceIntegrationTest.java, src/test/java/com/picktory/bundle/service/BundleServiceTest.java, src/test/java/com/picktory/bundle/service/BundleUpdateTest.java, src/test/java/com/picktory/user/service/UserServiceTest.java
> 
- User 엔티티의 kakaoId 필드 타입을 Long으로 변경
- 관련 테스트 코드 수정 (BundleService, UserService 등)
- String.valueOf() 호출 제거
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: kakaoId 타입을 String에서 Long으로 변경

src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/common/error/handler/GlobalExceptionHandler.java, src/main/java/com/picktory/domain/bundle/controller/BundleController.java, src/main/java/com/picktory/domain/bundle/dto/BundleSummaryResponse.java, src/main/java/com/picktory/domain/bundle/dto/GiftThumbnailResponse.java, src/main/java/com/picktory/domain/bundle/enums/DesignType.java, src/main/java/com/picktory/domain/bundle/service/BundleService.java, src/main/java/com/picktory/domain/gift/dto/GiftResponse.java
> 보따리 최초 생성 api를 최종 수정하였습니다.
> # 15. 보따리 생성 API
> POST /api/v1/bundles
> 
> ### 설명
> - bundleId == null인 경우 → 새로운 보따리를 생성하는 API
> - 임시저장, 보따리 배달 시 모두 사용 가능
> - **보따리 이름(name)**과 **디자인 타입(designType)**을 필수로 지정해야 함
> - 최소 2개 이상의 선물을 포함해야 함
> - **프론트의 req`imageUrls[0]`가 썸네일로서(isPrimary=true)로 저장됨**
> - 썸네일을 res로 제공하지 않고 전체 imageurls를 반환합니다.
> 
> 예시:
=> 보따리 생성(최초 생성) 수정 완료

src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/config/s3/S3Config.java, src/main/java/com/picktory/domain/gift/controller/S3Controller.java, src/main/java/com/picktory/domain/gift/service/S3Service.java, src/test/java/com/picktory/gift/service/GiftServiceTest.java
> 프론트 요청으로, Content-Type: multipart/form-data로 이미지를 받아서 s3에 업로드 하는 형식으로 수정하여 구현했습니다.
Postman에서 이미지 업로드 테스트하여 s3에 이미지 정상적으로 생성된 것을 확인했습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
- [ㅇ] 테스트 코드를 작성하였나요?
- [ ㅇ] 관련 문서를 업데이트하였나요?
> 
> 예시:
=> s3 이미지 업로드 방식 Multipart로 수정

src/main/java/com/picktory/domain/bundle/entity/Bundle.java
> 배달용 링크를 null 허용 안 해놔서 DRAFT일 때 오류나서 수정함.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: 배달용링크 @Column(nullable = false) → nullable = true로 변경

src/main/java/com/picktory/domain/bundle/dto/BundleMainListResponse.java
> 메인에도 읽었는지 유무가 필요하다고 해서 BundleMainListResponse에 isRead 필드 추가했습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: BundleMainListResponse에 isRead 필드 추가

src/main/java/com/picktory/config/jwt/JwtAuthenticationFilter.java, src/main/java/com/picktory/domain/response/controller/ResponseController.java, src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [Feature/fix-bundle-view-auth] API 리팩토링

src/main/java/com/picktory/domain/bundle/service/BundleService.java, src/main/java/com/picktory/domain/gift/dto/DraftGiftsResponse.java
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: bundleId 추가하여 생긴 오류 해결

src/main/java/com/picktory/domain/bundle/service/BundleService.java
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [style]: 하루 최대 생성 보따리 개수 검사 비활성화 - 프론트 테스트를 위해

src/main/java/com/picktory/domain/response/service/ResponseService.java
> 프론트와의 동작 흐름 생각 차이로 인해, 보따리 풀어보기 시 COMPLETED 상태도 정상 처리로 급히 수정합니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: 보따리 풀어보기 시 COMPLETED 상태도 정상 처리로 수정

src/main/java/com/picktory/domain/response/service/ResponseService.java
> 응답 결과가 res dto에는 반환되지만, 디비에 저장되지 않는 문제가 발생하여, 서비스 로직에 적용돼있던 트랜젝션 readOnly 설정을 문제로 추정하여 수정했습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [refactor]: 응답 결과 서비스 로직에 적용돼있던 트랜젝션 readOnly 설정 수정

src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
> 보따리 풀어보기 ResponseTag 추가 급한 수정.
=> [hotfix]: 보따리 풀어보기 ResponseTag 추가

src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/domain/response/dto/SaveGiftResponsesRequest.java, src/main/java/com/picktory/domain/response/service/ResponseService.java
번들 ID와 링크(UUID)의 개념을 명확히 분리하고, 이를 API 요청 및 서비스 로직에 반영한 리팩토링입니다.
- 없음
- 해당 없음
=> [refactor]: SaveGiftResponsesRequest에 bundleId 타입 에러 수정 및 검증 로직 분리

src/main/java/com/picktory/domain/auth/jwt/JwtTokenProvider.java, src/main/java/com/picktory/domain/auth/service/AuthService.java
- 리프레시 토큰에 사용자 ID 추가
- AuthService에서 리프레시 토큰 만료 시간 수정
- 토큰 재발급 시 인증 정보 유지 개선
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: JWT 토큰 관리 개선

build.gradle, src/main/java/com/picktory/domain/auth/service/AuthService.java
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [Fix]: 리프레시 토큰 에러 로그 출력

src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
Reverts dnd-side-project/dnd-12th-5-backend#87
=> Revert "[refactor]: ResponseBundleDto 필드 카멜 케이스 네이밍 적용"

src/main/java/com/picktory/common/BaseResponseStatus.java, src/main/java/com/picktory/domain/response/dto/SaveGiftResponsesRequest.java, src/main/java/com/picktory/domain/response/service/ResponseService.java
Reverts dnd-side-project/dnd-12th-5-backend#88
=> Revert "[refactor]: SaveGiftResponsesRequest에 bundleId 타입 에러 수정 및 검증 로직 분리"

src/main/java/com/picktory/domain/auth/jwt/JwtTokenProvider.java, src/main/java/com/picktory/domain/auth/service/AuthService.java
Reverts dnd-side-project/dnd-12th-5-backend#89
=> Revert "[fix]: JWT 토큰 관리 개선"

src/main/java/com/picktory/domain/response/dto/ResponseBundleDto.java
> 스네이크 케이스에서 카멜케이스로 수정 완료
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: 스네이크 케이스로 인한 오류 수정

src/main/java/com/picktory/domain/auth/jwt/JwtTokenProvider.java
- TokenDto에 refreshTokenExpiresIn 필드 추가
- JwtTokenProvider에서 리프레시 토큰 생성 시 userId 포함하도록 수정
- RefreshTokenService에서 토큰 업데이트 시 save 메서드 명시적 호출 추가
- 에러 메시지를 API 명세서와 일치하도록 수정
- 테스트 코드 업데이트
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: 리프레시 토큰 관련 버그 수정 및 API 명세서 일치화

src/main/java/com/picktory/config/SecurityConfig.java
> SecurityConfig에 PATCH 메소드를 ALLOWED_METHODS에 추가하여
임시저장된 보따리 이름 수정 API에서 발생하던 403 에러를 해결했습니다.
> - 변경사항 1
> - 변경사항 2
> - 변경사항 3
> 
> 예시:
=> [fix]: PATCH 메소드 CORS 설정 추가하여 보따리 이름 수정 API 403 에러 해결
